server:
  port: ${SERVER_PORT}

spring:
  application:
    name: geocoding-api

  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  elasticsearch:
    rest:
      uris: ${ELASTICSEARCH_URI}

