
server:
  port: 8082

spring:
  application:
    name: geocoding-api

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
  redis:
    host: localhost
    port: 6379
  elasticsearch:
    rest:
      uris: http://localhost:9200

springdoc:
  paths-to-match: /api/v1/**
  api-docs:
    path: /api-docs-json
  swagger-ui:
    path: /api-docs
