spring:
  kafka:
    bootstrap-servers: 'localhost:9092'

infrastructure:
  osm:
    filePath: "/home/nalhin/Desktop/Navigation/data/map-data.osm"
  topics:
    address: "exporter.address"
    street-connections: "exporter.street-connections"
    street-nodes: "exporter.street-nodes"
