server:
  port: 8081

spring:
  application:
    name: reverse-geocoding-api
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost

  data:
    mongodb:
      database: reverseGeocoding
      port: 27018
      host: localhost
