version: '3.8'
services:
  mongodb_pathfinding:
    image: mongo:4.4.5
    ports:
      - 27017:27017
    volumes:
      - mongodb_pathfinding_prod:/data/db
      - ./mongo/mongo-init-pathfinding.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: pathfinding

  mongodb_reverse_geocoding:
    image: mongo:4.4.5
    ports:
      - 27018:27017
    volumes:
      - mongodb_reverse_geocoding_prod:/data/db
      - ./mongo/mongo-init-reverse-geocoding.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: reverseGeocoding

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    volumes:
      - elastic_prod:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.4
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.5.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  kafka-connect:
    image: confluentinc/cp-kafka-connect:5.5.4
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8090:8090
    environment:
      CONNECT_REST_PORT: 8090
      CONNECT_ZOOKEEPER_CONNECT: "zookeeper:2181"
      CONNECT_BOOTSTRAP_SERVERS: "kafka:29092"
      CONNECT_GROUP_ID: connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: connect.configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: connect.offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: connect.status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 'false'
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_PLUGIN_PATH: /usr/share/java,/tmp/connect-plugins,/usr/share/confluent-hub-components
    command:
      - bash
      - -c
      - |
        confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:5.5.4
        confluent-hub install --no-prompt mongodb/kafka-connect-mongodb:1.4.0
        /etc/confluent/docker/run

  kafka-gui:
    image: obsidiandynamics/kafdrop:3.27.0
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"

  consul:
    image: consul:1.9.5
    ports:
      - 8500:8500

  redis:
    image: redis:6.0.9-alpine
    ports:
      - 6379:6379

  osm-data-processor-service:
    build: ../backend/services/osm-data-processor-service
    volumes:
      - ../data:/data/osm
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      OSM_FILE_PATH: /data/osm/osm-data.osm.bz2
      SPRING_PROFILES_ACTIVE: prod

  geocoding-service:
    build: ../backend/services/geocoding-service
    depends_on:
      - elasticsearch
      - consul
      - redis
    environment:
      SERVER_PORT: 8082
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_URI: http://elasticsearch:9200
      SPRING_PROFILES_ACTIVE: prod

  pathfinding-service:
    build: ../backend/services/pathfinding-service
    depends_on:
      - mongodb_pathfinding
      - consul
    environment:
      SERVER_PORT: 8083
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      MONGO_DATABASE: pathfinding
      MONGO_PORT: 27017
      MONGO_HOST: mongodb_pathfinding
      SPRING_PROFILES_ACTIVE: prod

  reverse-geocoding-service:
    build: ../backend/services/reverse-geocoding-service
    depends_on:
      - mongodb_reverse_geocoding
      - consul
    environment:
      SERVER_PORT: 8083
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      MONGO_DATABASE: reverseGeocoding
      MONGO_PORT: 27017
      MONGO_HOST: mongodb_reverse_geocoding
      SPRING_PROFILES_ACTIVE: prod

  gateway-service:
    build: ../backend/services/gateway
    ports:
      - "8000:8000"
    environment:
      SERVER_PORT: 8000
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      SPRING_PROFILES_ACTIVE: prod

  client:
    build: ../client
    depends_on:
      - gateway-service
    ports:
      - "3000:8080"
    environment:
      API_URI: http://gateway-service:8000

volumes:
  elastic_prod:
  mongodb_pathfinding_prod:
  mongodb_reverse_geocoding_prod:
