version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  elastic: