server:
  port: 8083

spring:
  application:
    name: pathfinding-api
  data:
    mongodb:
      database: pathfinding
      port: 27017
      host: localhost

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost

